export const FEATURES = [
  {
    tag: 'AI MENTOR',
    icon: 'psychology',
    headline: 'A coach that knows your weak spots',
    body: "Tracks assessment scores, planner completion, and DSA streak. Shifts tone based on whether you're ahead or falling behind — firm when behind, encouraging when on track.",
    stat: 'Powered by Gemini Flash',
    color: '#89ceff',
    shadow: 'rgba(137,206,255,0.15)',
    cta: 'INITIALIZE MENTOR',
  },
  {
    tag: 'WEEKLY PLANNER',
    icon: 'calendar_today',
    headline: 'Your week, built around your goals',
    body: 'AI generates a role-specific 7-day plan from skill gaps. Tell it your available hours today and it builds a daily schedule from weekly tasks — custom additions included.',
    stat: '7–10 tasks per week',
    color: '#34d399',
    shadow: 'rgba(52,211,153,0.15)',
    cta: 'SYNC SCHEDULE',
  },
  {
    tag: 'INTERVIEW HUB',
    icon: 'terminal',
    headline: '33,807 questions. Filtered to your role.',
    body: 'DSA problems, Q&A, and MCQ — filterable by role, skill, difficulty, and company. Ask the AI Teacher to explain any topic and it pulls real questions from the hub.',
    stat: '3,632 DSA · 5,816 MCQ · 33k+ Q&A',
    color: '#f472b6',
    shadow: 'rgba(244,114,182,0.15)',
    cta: 'LAUNCH HUB',
  },
  {
    tag: 'RESUME ANALYSER',
    icon: 'description',
    headline: 'ATS score in under 10 seconds',
    body: 'Upload your PDF — pdfminer extracts text, Gemini scores against your target role. Scanned copies go through Gemini Vision. Analysis history saved for comparison.',
    stat: 'Role-specific ATS scoring',
    color: '#fb923c',
    shadow: 'rgba(251,146,60,0.15)',
    cta: 'SCAN RESUME',
  },
  {
    tag: 'KNOWLEDGE VAULT',
    icon: 'token',
    headline: "One place for everything you've saved",
    body: 'Bookmark DSA problems, save AI insights from mentor sessions, write personal notes on any question. One polymorphic feed — everything linked back to its source.',
    stat: 'Bookmarks · Insights · Notes',
    color: '#bdc2ff',
    shadow: 'rgba(189,194,255,0.15)',
    cta: 'OPEN VAULT',
  },
];

export const STEPS = [
  { n: '01', icon: 'person_search', color: '#89ceff', title: 'Profile & Assessment',      body: 'Set your target role, companies, and self-rate your confidence across DSA and core subjects.' },
  { n: '02', icon: 'map',           color: '#7bd0ff', title: 'AI Generates Your Roadmap', body: 'Gemini builds a personalised weekly plan based on your skill gaps and target companies.' },
  { n: '03', icon: 'model_training', color: '#bdc2ff', title: 'Practise in the Hub',      body: 'Work through DSA problems, Q&A, and MCQ filtered to your role. Ask the AI Teacher anything.' },
  { n: '04', icon: 'verified',       color: '#f472b6', title: 'Track and Improve',        body: 'Dashboard readiness score updates live. Upload your resume for ATS feedback anytime.' },
];
