"""add_audit_columns_to_resume_analyses

Revision ID: 4382eb22535d
Revises: b7fc7ca14f99
Create Date: 2026-09-24 15:05:13.781784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4382eb22535d'
down_revision: Union[str, Sequence[str], None] = 'b7fc7ca14f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iq_fts'), table_name='interview_questions', postgresql_using='gin')
    op.create_index('ix_iq_fts', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.add_column('resume_analyses', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('resume_analyses', sa.Column('prompt_version', sa.String(length=30), nullable=True))
    op.add_column('resume_analyses', sa.Column('scoring_version', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analyses', 'scoring_version')
    op.drop_column('resume_analyses', 'prompt_version')
    op.drop_column('resume_analyses', 'model')
    op.drop_index('ix_iq_fts', table_name='interview_questions', postgresql_using='gin')
    op.create_index(op.f('ix_iq_fts'), 'interview_questions', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
