"""Add role and category columns to user_skill_assessments

Revision ID: 5cc12e0df866
Revises: f71487121852
Create Date: 2026-09-11 10:19:31.102944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc12e0df866'
down_revision: Union[str, Sequence[str], None] = 'f71487121852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iq_fts'), table_name='interview_questions', postgresql_using='gin')
    op.create_index('ix_iq_fts', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.add_column('user_skill_assessments', sa.Column('category', sa.String(length=60), nullable=True))
    op.add_column('user_skill_assessments', sa.Column('role', sa.String(length=80), nullable=True))
    op.create_index('ix_usa_user_role', 'user_skill_assessments', ['user_id', 'role'], unique=False)
    op.create_unique_constraint('uq_usa_user_role_skill', 'user_skill_assessments', ['user_id', 'role', 'skill_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usa_user_role_skill', 'user_skill_assessments', type_='unique')
    op.drop_index('ix_usa_user_role', table_name='user_skill_assessments')
    op.drop_column('user_skill_assessments', 'role')
    op.drop_column('user_skill_assessments', 'category')
    op.drop_index('ix_iq_fts', table_name='interview_questions', postgresql_using='gin')
    op.create_index(op.f('ix_iq_fts'), 'interview_questions', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
