"""add ai indexes

Revision ID: 5f16a1b333ee
Revises: ed54bccf091a
Create Date: 2026-07-13 13:02:50.927931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f16a1b333ee'
down_revision: Union[str, Sequence[str], None] = 'ed54bccf091a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iq_fts'), table_name='interview_questions', postgresql_using='gin')
    op.create_index('ix_iq_fts', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_mm_conv_created', 'mentor_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_pg_user_status', 'planner_generations', ['user_id', 'status'], unique=False)
    op.create_index('ix_pt_plan_status', 'planner_tasks', ['weekly_plan_id', 'status'], unique=False)
    op.create_index('ix_pt_user_due', 'planner_tasks', ['user_id', 'due_date'], unique=False)
    op.create_index('ix_usa_user_confidence', 'user_skill_assessments', ['user_id', 'self_rated_confidence'], unique=False)
    op.create_index('ix_user_target_role', 'users', ['target_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_target_role', table_name='users')
    op.drop_index('ix_usa_user_confidence', table_name='user_skill_assessments')
    op.drop_index('ix_pt_user_due', table_name='planner_tasks')
    op.drop_index('ix_pt_plan_status', table_name='planner_tasks')
    op.drop_index('ix_pg_user_status', table_name='planner_generations')
    op.drop_index('ix_mm_conv_created', table_name='mentor_messages')
    op.drop_index('ix_iq_fts', table_name='interview_questions', postgresql_using='gin')
    op.create_index(op.f('ix_iq_fts'), 'interview_questions', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
