"""Add InterviewHub and Knowledge Vault models

Revision ID: 9d8da3055bed
Revises: e28044ec865c
Create Date: 2026-07-03 19:30:08.745754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d8da3055bed'
down_revision: Union[str, Sequence[str], None] = 'e28044ec865c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsa_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frontend_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('titleSlug', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('code_snippets', sa.Text(), nullable=True),
    sa.Column('acRate', sa.Float(), nullable=True),
    sa.Column('companies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('problem_URL', sa.String(length=500), nullable=True),
    sa.Column('is_premium', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dsa_companies', 'dsa_problems', ['companies'], unique=False, postgresql_using='gin')
    op.create_index('idx_dsa_search', 'dsa_problems', [sa.literal_column("to_tsvector('english', title)")], unique=False, postgresql_using='gin')
    op.create_index('idx_dsa_topic_tags', 'dsa_problems', ['topic_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_dsa_problems_difficulty'), 'dsa_problems', ['difficulty'], unique=False)
    op.create_index(op.f('ix_dsa_problems_frontend_id'), 'dsa_problems', ['frontend_id'], unique=True)
    op.create_index(op.f('ix_dsa_problems_id'), 'dsa_problems', ['id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_category_difficulty', 'interview_questions', ['category', 'difficulty'], unique=False)
    op.create_index('idx_interview_roles', 'interview_questions', ['roles'], unique=False, postgresql_using='gin')
    op.create_index('idx_interview_search', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || body)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_interview_questions_category'), 'interview_questions', ['category'], unique=False)
    op.create_index(op.f('ix_interview_questions_difficulty'), 'interview_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=True),
    sa.Column('option_b', sa.Text(), nullable=True),
    sa.Column('option_c', sa.Text(), nullable=True),
    sa.Column('option_d', sa.Text(), nullable=True),
    sa.Column('correct_ans', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_search', 'quiz_questions', [sa.literal_column("to_tsvector('english', question)")], unique=False, postgresql_using='gin')
    op.create_index('idx_quiz_section_topic', 'quiz_questions', ['section', 'topic'], unique=False)
    op.create_index(op.f('ix_quiz_questions_difficulty'), 'quiz_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_section'), 'quiz_questions', ['section'], unique=False)
    op.create_index(op.f('ix_quiz_questions_topic'), 'quiz_questions', ['topic'], unique=False)
    op.create_table('user_coding_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dsa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dsa_id'], ['dsa_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_coding_uid', 'user_coding_progress', ['user_id'], unique=False)
    op.create_index('idx_user_coding_uid_qid', 'user_coding_progress', ['user_id', 'dsa_id'], unique=False)
    op.create_index('idx_user_coding_uid_status', 'user_coding_progress', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_coding_progress_id'), 'user_coding_progress', ['id'], unique=False)
    op.create_table('user_question_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interview_q_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_q_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_iq_uid', 'user_question_progress', ['user_id'], unique=False)
    op.create_index('idx_user_iq_uid_qid', 'user_question_progress', ['user_id', 'interview_q_id'], unique=False)
    op.create_index('idx_user_iq_uid_status', 'user_question_progress', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_question_progress_id'), 'user_question_progress', ['id'], unique=False)
    op.create_table('user_quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_quiz_uid', 'user_quiz_attempts', ['user_id'], unique=False)
    op.create_index('idx_user_quiz_uid_correct', 'user_quiz_attempts', ['user_id', 'is_correct'], unique=False)
    op.create_index('idx_user_quiz_uid_qid', 'user_quiz_attempts', ['user_id', 'quiz_id'], unique=False)
    op.create_index(op.f('ix_user_quiz_attempts_id'), 'user_quiz_attempts', ['id'], unique=False)
    op.create_table('vault_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('BOOKMARK', 'AI_INSIGHT', 'PERSONAL_NOTE', name='vaultitemtype'), nullable=False),
    sa.Column('reference_type', sa.Enum('DSA', 'QUIZ', 'INTERVIEW', 'NONE', name='vaultreferencetype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vault_reference', 'vault_items', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_vault_user_created', 'vault_items', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_vault_items_id'), 'vault_items', ['id'], unique=False)
    op.create_index(op.f('ix_vault_items_item_type'), 'vault_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_vault_items_user_id'), 'vault_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_items_user_id'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_item_type'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_id'), table_name='vault_items')
    op.drop_index('idx_vault_user_created', table_name='vault_items')
    op.drop_index('idx_vault_reference', table_name='vault_items')
    op.drop_table('vault_items')
    op.drop_index(op.f('ix_user_quiz_attempts_id'), table_name='user_quiz_attempts')
    op.drop_index('idx_user_quiz_uid_qid', table_name='user_quiz_attempts')
    op.drop_index('idx_user_quiz_uid_correct', table_name='user_quiz_attempts')
    op.drop_index('idx_user_quiz_uid', table_name='user_quiz_attempts')
    op.drop_table('user_quiz_attempts')
    op.drop_index(op.f('ix_user_question_progress_id'), table_name='user_question_progress')
    op.drop_index('idx_user_iq_uid_status', table_name='user_question_progress')
    op.drop_index('idx_user_iq_uid_qid', table_name='user_question_progress')
    op.drop_index('idx_user_iq_uid', table_name='user_question_progress')
    op.drop_table('user_question_progress')
    op.drop_index(op.f('ix_user_coding_progress_id'), table_name='user_coding_progress')
    op.drop_index('idx_user_coding_uid_status', table_name='user_coding_progress')
    op.drop_index('idx_user_coding_uid_qid', table_name='user_coding_progress')
    op.drop_index('idx_user_coding_uid', table_name='user_coding_progress')
    op.drop_table('user_coding_progress')
    op.drop_index(op.f('ix_quiz_questions_topic'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_section'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_difficulty'), table_name='quiz_questions')
    op.drop_index('idx_quiz_section_topic', table_name='quiz_questions')
    op.drop_index('idx_quiz_search', table_name='quiz_questions', postgresql_using='gin')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_difficulty'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_category'), table_name='interview_questions')
    op.drop_index('idx_interview_search', table_name='interview_questions', postgresql_using='gin')
    op.drop_index('idx_interview_roles', table_name='interview_questions', postgresql_using='gin')
    op.drop_index('idx_interview_category_difficulty', table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_dsa_problems_id'), table_name='dsa_problems')
    op.drop_index(op.f('ix_dsa_problems_frontend_id'), table_name='dsa_problems')
    op.drop_index(op.f('ix_dsa_problems_difficulty'), table_name='dsa_problems')
    op.drop_index('idx_dsa_topic_tags', table_name='dsa_problems', postgresql_using='gin')
    op.drop_index('idx_dsa_search', table_name='dsa_problems', postgresql_using='gin')
    op.drop_index('idx_dsa_companies', table_name='dsa_problems', postgresql_using='gin')
    op.drop_table('dsa_problems')
    # ### end Alembic commands ###
