"""Add stateful conversation fields

Revision ID: d092f448052f
Revises: 5cc12e0df866
Create Date: 2026-09-11 11:30:09.112769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd092f448052f'
down_revision: Union[str, Sequence[str], None] = '5cc12e0df866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iq_fts'), table_name='interview_questions', postgresql_using='gin')
    op.create_index('ix_iq_fts', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.add_column('mentor_conversations', sa.Column('agent_mode', sa.String(length=20), nullable=True))
    op.add_column('mentor_conversations', sa.Column('active_topic', sa.String(length=200), nullable=True))
    op.add_column('mentor_conversations', sa.Column('current_task', sa.String(length=50), nullable=False, server_default='general'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor_conversations', 'current_task')
    op.drop_column('mentor_conversations', 'active_topic')
    op.drop_column('mentor_conversations', 'agent_mode')
    op.drop_index('ix_iq_fts', table_name='interview_questions', postgresql_using='gin')
    op.create_index(op.f('ix_iq_fts'), 'interview_questions', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
