"""add dashboard_statistics weekly_plans planner_tasks

Revision ID: e28044ec865c
Revises: efae8c76bf9c
Create Date: 2026-06-28 15:57:00.171049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28044ec865c'
down_revision: Union[str, Sequence[str], None] = 'efae8c76bf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_statistics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planner_completion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dsa_solved', sa.Integer(), nullable=True),
    sa.Column('subjects_completed', sa.Integer(), nullable=True),
    sa.Column('github_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resume_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('applications_sent', sa.Integer(), nullable=True),
    sa.Column('interviews_completed', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('generation_source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_id'), 'weekly_plans', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_table('planner_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_tasks_id'), 'planner_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_planner_tasks_user_id'), 'planner_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_planner_tasks_weekly_plan_id'), 'planner_tasks', ['weekly_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planner_tasks_weekly_plan_id'), table_name='planner_tasks')
    op.drop_index(op.f('ix_planner_tasks_user_id'), table_name='planner_tasks')
    op.drop_index(op.f('ix_planner_tasks_id'), table_name='planner_tasks')
    op.drop_table('planner_tasks')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_table('dashboard_statistics')
    # ### end Alembic commands ###
