"""Add updated hub models

Revision ID: ed54bccf091a
Revises: 9d8da3055bed
Create Date: 2026-07-04 20:44:31.283410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed54bccf091a'
down_revision: Union[str, Sequence[str], None] = '9d8da3055bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsa_problems', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('dsa_problems', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('interview_questions', sa.Column('skill', sa.String(length=120), nullable=True))
    op.add_column('interview_questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('interview_questions', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interview_questions', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('interview_questions', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('interview_questions', 'source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=40),
               nullable=False)
    op.drop_index(op.f('idx_interview_category_difficulty'), table_name='interview_questions')
    op.drop_index(op.f('idx_interview_roles'), table_name='interview_questions', postgresql_using='gin')
    op.drop_index(op.f('idx_interview_search'), table_name='interview_questions', postgresql_using='gin')
    op.create_index(op.f('ix_interview_questions_skill'), 'interview_questions', ['skill'], unique=False)
    op.create_index('ix_iq_category_difficulty', 'interview_questions', ['category', 'difficulty'], unique=False)
    op.create_index('ix_iq_category_skill', 'interview_questions', ['category', 'skill'], unique=False)
    op.create_index('ix_iq_fts', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_iq_roles_gin', 'interview_questions', ['roles'], unique=False, postgresql_using='gin')
    op.add_column('quiz_questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('quiz_questions', 'section',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'topic',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'option_a',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('quiz_questions', 'option_b',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('quiz_questions', 'option_c',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('quiz_questions', 'option_d',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('quiz_questions', 'correct_ans',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.drop_index(op.f('idx_quiz_search'), table_name='quiz_questions', postgresql_using='gin')
    op.drop_index(op.f('idx_quiz_section_topic'), table_name='quiz_questions')
    op.create_index('ix_quiz_section_difficulty', 'quiz_questions', ['section', 'difficulty'], unique=False)
    op.create_index('ix_quiz_section_topic', 'quiz_questions', ['section', 'topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_section_topic', table_name='quiz_questions')
    op.drop_index('ix_quiz_section_difficulty', table_name='quiz_questions')
    op.create_index(op.f('idx_quiz_section_topic'), 'quiz_questions', ['section', 'topic'], unique=False)
    op.create_index(op.f('idx_quiz_search'), 'quiz_questions', [sa.literal_column("to_tsvector('english'::regconfig, question)")], unique=False, postgresql_using='gin')
    op.alter_column('quiz_questions', 'correct_ans',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'option_d',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('quiz_questions', 'option_c',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('quiz_questions', 'option_b',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('quiz_questions', 'option_a',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('quiz_questions', 'difficulty',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'topic',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'section',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('quiz_questions', 'created_at')
    op.drop_index('ix_iq_roles_gin', table_name='interview_questions', postgresql_using='gin')
    op.drop_index('ix_iq_fts', table_name='interview_questions', postgresql_using='gin')
    op.drop_index('ix_iq_category_skill', table_name='interview_questions')
    op.drop_index('ix_iq_category_difficulty', table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_skill'), table_name='interview_questions')
    op.create_index(op.f('idx_interview_search'), 'interview_questions', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || body)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_interview_roles'), 'interview_questions', ['roles'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_interview_category_difficulty'), 'interview_questions', ['category', 'difficulty'], unique=False)
    op.alter_column('interview_questions', 'source',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('interview_questions', 'difficulty',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('interview_questions', 'category',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('interview_questions', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('interview_questions', 'created_at')
    op.drop_column('interview_questions', 'skill')
    op.alter_column('dsa_problems', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('dsa_problems', 'created_at')
    # ### end Alembic commands ###
