"""Drop obsolete planner_generations table

Revision ID: f71487121852
Revises: e3893560a26e
Create Date: 2026-09-08 17:59:58.139378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f71487121852'
down_revision: Union[str, Sequence[str], None] = 'e3893560a26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_quiz_uid'), table_name='user_quiz_attempts')
    op.drop_index(op.f('idx_user_quiz_uid_correct'), table_name='user_quiz_attempts')
    op.drop_index(op.f('idx_user_quiz_uid_qid'), table_name='user_quiz_attempts')
    op.drop_index(op.f('ix_user_quiz_attempts_id'), table_name='user_quiz_attempts')
    op.drop_table('user_quiz_attempts')
    op.drop_index(op.f('ix_pg_user_status'), table_name='planner_generations')
    op.drop_index(op.f('ix_planner_generations_id'), table_name='planner_generations')
    op.drop_index(op.f('ix_planner_generations_user_id'), table_name='planner_generations')
    op.drop_table('planner_generations')
    op.drop_index(op.f('idx_user_iq_uid'), table_name='user_question_progress')
    op.drop_index(op.f('idx_user_iq_uid_qid'), table_name='user_question_progress')
    op.drop_index(op.f('idx_user_iq_uid_status'), table_name='user_question_progress')
    op.drop_index(op.f('ix_user_question_progress_id'), table_name='user_question_progress')
    op.drop_table('user_question_progress')
    op.drop_index(op.f('ix_iq_fts'), table_name='interview_questions', postgresql_using='gin')
    op.create_index('ix_iq_fts', 'interview_questions', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.drop_column('planner_tasks', 'ai_generated')
    op.drop_column('planner_tasks', 'reminder_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planner_tasks', sa.Column('reminder_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('planner_tasks', sa.Column('ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index('ix_iq_fts', table_name='interview_questions', postgresql_using='gin')
    op.create_index(op.f('ix_iq_fts'), 'interview_questions', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    op.create_table('user_question_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interview_q_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_q_id'], ['interview_questions.id'], name=op.f('user_question_progress_interview_q_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_question_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_question_progress_pkey'))
    )
    op.create_index(op.f('ix_user_question_progress_id'), 'user_question_progress', ['id'], unique=False)
    op.create_index(op.f('idx_user_iq_uid_status'), 'user_question_progress', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_user_iq_uid_qid'), 'user_question_progress', ['user_id', 'interview_q_id'], unique=False)
    op.create_index(op.f('idx_user_iq_uid'), 'user_question_progress', ['user_id'], unique=False)
    op.create_table('planner_generations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weekly_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('planner_generations_user_id_fkey')),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], name=op.f('planner_generations_weekly_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('planner_generations_pkey'))
    )
    op.create_index(op.f('ix_planner_generations_user_id'), 'planner_generations', ['user_id'], unique=False)
    op.create_index(op.f('ix_planner_generations_id'), 'planner_generations', ['id'], unique=False)
    op.create_index(op.f('ix_pg_user_status'), 'planner_generations', ['user_id', 'status'], unique=False)
    op.create_table('user_quiz_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('selected_option', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_questions.id'], name=op.f('user_quiz_attempts_quiz_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_quiz_attempts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_quiz_attempts_pkey'))
    )
    op.create_index(op.f('ix_user_quiz_attempts_id'), 'user_quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('idx_user_quiz_uid_qid'), 'user_quiz_attempts', ['user_id', 'quiz_id'], unique=False)
    op.create_index(op.f('idx_user_quiz_uid_correct'), 'user_quiz_attempts', ['user_id', 'is_correct'], unique=False)
    op.create_index(op.f('idx_user_quiz_uid'), 'user_quiz_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###
